# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  directory:  # id of input
    description: 'Who to greet'
    required: false
    default: '.'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
